[UI]
# The display name of your app & chatbot
name                   = "Chat with Jun Le"
# GitHub icon/link in the header
github                 = "https://github.com/driedsoba"

# control Chain-of-Thought visibility ("hidden" | "tool_call" | "full")
cot                    = "full"
# large content collapsed by default
default_collapse_content = true
# sub-messages expanded by default
default_expand_messages  = false

login_page_image = "/public/background.jpg"

